# Generated by Django 4.0.1 on 2022-01-18 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=300, unique=True, verbose_name='Наименование канала')),
                ('object_a', models.CharField(max_length=100, verbose_name='Объект А')),
                ('object_b', models.CharField(max_length=100, verbose_name='Объект Б')),
                ('traffic', models.CharField(max_length=30, verbose_name='Трафик')),
                ('description', models.CharField(max_length=3000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=100, verbose_name='Оборудование')),
                ('description', models.CharField(max_length=200, verbose_name='Описание ')),
                ('channels_connect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels_conn', to='scheme.equipment', verbose_name='Прохождение каналов')),
            ],
            options={
                'verbose_name': 'Оборудованин',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True, verbose_name='Название объекта')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес объекта')),
                ('equipment_connect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_con', to='scheme.equipment', verbose_name='Прохождение по оборудованию')),
            ],
            options={
                'verbose_name': 'Объекты',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
