# Generated by Django 4.0.1 on 2022-01-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0002_remove_equipment_channels_connect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channels',
            name='equipment_connect',
        ),
        migrations.AddField(
            model_name='channels',
            name='equipment_connect',
            field=models.ManyToManyField(related_name='equipment_conn', to='scheme.Equipment', verbose_name='Оборудование'),
        ),
    ]
