# Generated by Django 4.0.1 on 2022-01-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0003_remove_channels_equipment_connect_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterField(
            model_name='channels',
            name='equipment_connect',
            field=models.ManyToManyField(related_name='equipment_con', to='scheme.Equipment', verbose_name='Оборудование'),
        ),
    ]
