# Generated by Django 4.0.1 on 2022-01-31 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0004_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='equipment_connect',
            field=models.ManyToManyField(related_name='equipmentcon', to='scheme.Equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='locations_connect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locationcon', to='scheme.locations', verbose_name='Прохождение по оборудованию'),
        ),
    ]
