# Generated by Django 4.0.1 on 2022-02-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0005_alter_channels_equipment_connect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='description',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='channels',
            name='traffic',
            field=models.CharField(blank=True, max_length=30, verbose_name='Трафик'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='locations_connect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='locationcon', to='scheme.locations', verbose_name='Прохождение по оборудованию'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locations',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес объекта'),
        ),
    ]
