# Generated by Django 4.0.1 on 2022-02-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0007_alter_equipment_equipment_specifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specifications',
            options={'verbose_name': 'Состав оборудования', 'verbose_name_plural': 'Состав оборудования'},
        ),
        migrations.AddField(
            model_name='specifications',
            name='channel_connect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channelcon', to='scheme.channels', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='specification',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='specificationcon', to='scheme.equipment', verbose_name='Спецификация'),
        ),
    ]
