# Generated by Django 3.1.3 on 2022-05-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0008_alter_specifications_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='id_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inv_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Инвентарный номер'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mount_cab',
            field=models.CharField(blank=True, max_length=200, verbose_name='Монтажный шкаф'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.CharField(blank=True, max_length=200, verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='channels',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='locations_connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locationcon', to='scheme.locations', verbose_name='Месторасположение'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
