# Generated by Django 4.0.1 on 2022-05-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0009_auto_20220523_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='channel_card',
            field=models.FileField(blank=True, null=True, upload_to='channel_card', verbose_name='Карточка канала'),
        ),
        migrations.AddField(
            model_name='channels',
            name='channel_scheme',
            field=models.FileField(blank=True, null=True, upload_to='channel_scheme', verbose_name='Схема канала'),
        ),
        migrations.AlterField(
            model_name='channels',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
